# Generated by Django 5.2.15 on 2026-06-10 04:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'ordering': ['name']},
        ),
        migrations.AddField(
            model_name='customer',
            name='loyalty_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='loyalty_points',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10),
        ),
        migrations.CreateModel(
            name='CreditProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('credit_limit', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('settlement_period_days', models.IntegerField(default=30)),
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='credit_profile', to='customers.customer')),
            ],
        ),
    ]
