# Generated by Django 5.2.15 on 2026-06-10 04:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_service',
            field=models.BooleanField(default=False, help_text='100% margin service item'),
        ),
        migrations.AddField(
            model_name='product',
            name='is_variable_weight',
            field=models.BooleanField(default=False, help_text='Tingi fractional quantity item'),
        ),
        migrations.AlterField(
            model_name='product',
            name='min_stock_level',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='stock_quantity',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10),
        ),
        migrations.CreateModel(
            name='RecipeIngredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_required', models.DecimalField(decimal_places=3, max_digits=10)),
                ('child_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='used_in_recipes', to='inventory.product')),
                ('parent_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipe_ingredients', to='inventory.product')),
            ],
            options={
                'unique_together': {('parent_product', 'child_product')},
            },
        ),
        migrations.AddField(
            model_name='product',
            name='components',
            field=models.ManyToManyField(through='inventory.RecipeIngredient', to='inventory.product'),
        ),
    ]
