# Generated by Django 5.2.15 on 2026-06-12 09:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_alter_inventoryreceipt_received_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorderitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_order_items', to='inventory.product'),
        ),
        migrations.AlterField(
            model_name='recipeingredient',
            name='child_product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='used_in_recipes', to='inventory.product'),
        ),
        migrations.AlterField(
            model_name='recipeingredient',
            name='parent_product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recipe_ingredients', to='inventory.product'),
        ),
    ]
