# Generated by Django 5.2.15 on 2026-06-12 09:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_alter_purchaseorderitem_product_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventoryreceiptitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='receipt_items', to='inventory.product'),
        ),
    ]
