# Generated by Django 5.2.15 on 2026-09-11 12:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_bundle_bundleitem'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryStockCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('POSTED', 'Posted')], default='DRAFT', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('posted_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='stock_counts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='InventoryAdjustment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('previous_qty', models.DecimalField(decimal_places=3, max_digits=10)),
                ('adjusted_qty', models.DecimalField(decimal_places=3, max_digits=10)),
                ('delta', models.DecimalField(decimal_places=3, max_digits=10)),
                ('reason', models.CharField(choices=[('PHYSICAL_COUNT', 'Physical count'), ('DAMAGED', 'Damaged goods'), ('EXPIRED', 'Expired'), ('FOUND', 'Found on shelf'), ('SHRINKAGE', 'Shrinkage'), ('OTHER', 'Other')], default='PHYSICAL_COUNT', max_length=20)),
                ('cost_price_at_adjustment', models.DecimalField(decimal_places=2, max_digits=12)),
                ('delta_cost_value', models.DecimalField(decimal_places=2, max_digits=14)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('adjusted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='stock_adjustments', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_adjustments', to='inventory.product')),
                ('stock_count', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='adjustments', to='inventory.inventorystockcount')),
            ],
        ),
    ]
