# Generated by Django 5.2.15 on 2026-10-05 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0010_inventorystockcount_inventoryadjustment'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Cleared when the product is archived: hidden from picking, checkout and stock screens, but kept so past sales, receipts and reports still resolve it.'),
        ),
    ]
