# Generated by Django 5.2.15 on 2026-06-10 04:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_alter_customer_options_customer_loyalty_enabled_and_more'),
        ('inventory', '0002_product_is_service_product_is_variable_weight_and_more'),
        ('sales', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('payment_type', models.CharField(choices=[('CASH', 'Cash'), ('CARD', 'Card'), ('STORE_CREDIT', 'Store Credit'), ('OWNER_DRAW', 'Owner Draw')], default='CASH', max_length=12)),
                ('payment_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('POSTED', 'Posted'), ('VOIDED', 'Voided')], default='POSTED', max_length=8)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('transaction_date', models.DateTimeField(help_text='Actual business date (user-inputtable for offline recovery)')),
                ('cashier', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='transactions', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='customers.customer')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='transactions', to='sales.session')),
            ],
        ),
        migrations.CreateModel(
            name='TransactionLineItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_sold', models.DecimalField(decimal_places=3, max_digits=10)),
                ('price_at_sale', models.DecimalField(decimal_places=2, max_digits=12)),
                ('cost_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='transaction_items', to='inventory.product')),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='items', to='sales.transaction')),
            ],
        ),
    ]
