# Generated by Django 5.2.15 on 2026-06-12 09:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_alter_purchaseorderitem_product_and_more'),
        ('sales', '0004_alter_session_closed_by_alter_session_opened_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactionlineitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transaction_items', to='inventory.product'),
        ),
    ]
