# Generated by Django 5.2.15 on 2026-07-06 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0005_alter_transactionlineitem_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='cash_count_breakdown',
            field=models.JSONField(blank=True, help_text='Per-denomination counts entered at session close', null=True),
        ),
    ]
