# Generated by Django 5.2.15 on 2026-10-07 04:53

from django.db import migrations, models


def store_credit_to_account(apps, schema_editor):
    Payment = apps.get_model('sales', 'Payment')
    Payment.objects.filter(payment_type='STORE_CREDIT').update(payment_type='ACCOUNT')


def account_to_store_credit(apps, schema_editor):
    Payment = apps.get_model('sales', 'Payment')
    Payment.objects.filter(payment_type='ACCOUNT').update(payment_type='STORE_CREDIT')


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0009_remove_transaction_payment_fields'),
    ]

    operations = [
        migrations.RunPython(store_credit_to_account, account_to_store_credit),
        migrations.AlterField(
            model_name='payment',
            name='payment_type',
            field=models.CharField(choices=[('CASH', 'Cash'), ('CARD', 'Card'), ('ACCOUNT', 'Account'), ('OWNER_DRAW', 'Owner Draw')], max_length=12),
        ),
    ]
