# Generated by Django 5.2.15 on 2026-06-10 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='pin_code',
            field=models.CharField(blank=True, help_text='Hashed PIN for cashier auth', max_length=128),
        ),
    ]
