# Generated by Django 5.2.15 on 2026-06-14 15:44

from django.db import migrations


def seed_default_settings(apps, schema_editor):
    SystemSetting = apps.get_model('core', 'SystemSetting')
    SystemSetting.objects.get_or_create(
        key='DEFAULT_MARKUP_RATE',
        defaults={
            'value': '0.15',
            'description': 'Default markup rate for suggested retail price calculations (e.g. 0.15 = 15%)',
        },
    )


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(seed_default_settings),
    ]

