# Generated by Django 5.2.15 on 2026-10-07 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_seed_default_customer_credit_limit'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessinfo',
            name='receipt_notes',
            field=models.TextField(blank=True, default='', verbose_name='Receipt Note'),
        ),
    ]
